### ISSUE TITLE
能提供一个armv7l 32的版本吗

### ISSUE THREAD

**Issue by Somalia0932** [KincaidYang/whois#2]
能提供一个armv7l 32的版本吗？

**Comment by KincaidYang** [comment]
我刚刚发布了一个版本，你可以试一下，我没有相关的设备能够验证https://github.com/KincaidYang/whois/releases/download/v0.2.5/whois_0.2.5_linux_arm.tar.gz

**Comment by Somalia0932** [comment]
> 我刚刚发布了一个版本，你可以试一下，我没有相关的设备能够验证https://github.com/KincaidYang/whois/releases/download/v0.2.5/whois_0.2.5_linux_arm.tar.gz

已结验证，可以用了，谢谢大佬
